#!/bin/bash

#####################################
#
# NOMBRE: 
# OBJETIVO
# AUTOR: Jaime León <jaimeleongarcia123@gmail.com>
# ARGUMENTOS: Ninguno
# SALIDAS: 
# 
# FECHA:
# VERSIÓN: 1.0 (código inicial)
# 
#####################################
